/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedShoppingRouteImport } from './routes/_authed/shopping'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedMealsIndexRouteImport } from './routes/_authed/meals/index'
import { Route as AuthedTasksNewRouteImport } from './routes/_authed/tasks/new'
import { Route as AuthedMealsNewRouteImport } from './routes/_authed/meals/new'
import { Route as AuthedMembersMemberIdIndexRouteImport } from './routes/_authed/members/$memberId.index'
import { Route as AuthedTasksTaskIdEditRouteImport } from './routes/_authed/tasks/$taskId.edit'
import { Route as AuthedSettingsMembersNewRouteImport } from './routes/_authed/settings/members.new'
import { Route as AuthedMembersMemberIdChoresRouteImport } from './routes/_authed/members/$memberId.chores'
import { Route as AuthedMealsMealIdEditRouteImport } from './routes/_authed/meals/$mealId.edit'
import { Route as AuthedSettingsMembersMemberIdEditRouteImport } from './routes/_authed/settings/members.$memberId.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShoppingRoute = AuthedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMealsIndexRoute = AuthedMealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksNewRoute = AuthedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMealsNewRoute = AuthedMealsNewRouteImport.update({
  id: '/meals/new',
  path: '/meals/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersMemberIdIndexRoute =
  AuthedMembersMemberIdIndexRouteImport.update({
    id: '/members/$memberId/',
    path: '/members/$memberId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTasksTaskIdEditRoute = AuthedTasksTaskIdEditRouteImport.update({
  id: '/tasks/$taskId/edit',
  path: '/tasks/$taskId/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsMembersNewRoute =
  AuthedSettingsMembersNewRouteImport.update({
    id: '/settings/members/new',
    path: '/settings/members/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedMembersMemberIdChoresRoute =
  AuthedMembersMemberIdChoresRouteImport.update({
    id: '/members/$memberId/chores',
    path: '/members/$memberId/chores',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedMealsMealIdEditRoute = AuthedMealsMealIdEditRouteImport.update({
  id: '/meals/$mealId/edit',
  path: '/meals/$mealId/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsMembersMemberIdEditRoute =
  AuthedSettingsMembersMemberIdEditRouteImport.update({
    id: '/settings/members/$memberId/edit',
    path: '/settings/members/$memberId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/calendar': typeof AuthedCalendarRoute
  '/shopping': typeof AuthedShoppingRoute
  '/': typeof AuthedIndexRoute
  '/meals/new': typeof AuthedMealsNewRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/meals': typeof AuthedMealsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/meals/$mealId/edit': typeof AuthedMealsMealIdEditRoute
  '/members/$memberId/chores': typeof AuthedMembersMemberIdChoresRoute
  '/settings/members/new': typeof AuthedSettingsMembersNewRoute
  '/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/members/$memberId': typeof AuthedMembersMemberIdIndexRoute
  '/settings/members/$memberId/edit': typeof AuthedSettingsMembersMemberIdEditRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/calendar': typeof AuthedCalendarRoute
  '/shopping': typeof AuthedShoppingRoute
  '/': typeof AuthedIndexRoute
  '/meals/new': typeof AuthedMealsNewRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/meals': typeof AuthedMealsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/meals/$mealId/edit': typeof AuthedMealsMealIdEditRoute
  '/members/$memberId/chores': typeof AuthedMembersMemberIdChoresRoute
  '/settings/members/new': typeof AuthedSettingsMembersNewRoute
  '/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/members/$memberId': typeof AuthedMembersMemberIdIndexRoute
  '/settings/members/$memberId/edit': typeof AuthedSettingsMembersMemberIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/shopping': typeof AuthedShoppingRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/meals/new': typeof AuthedMealsNewRoute
  '/_authed/tasks/new': typeof AuthedTasksNewRoute
  '/_authed/meals/': typeof AuthedMealsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
  '/_authed/meals/$mealId/edit': typeof AuthedMealsMealIdEditRoute
  '/_authed/members/$memberId/chores': typeof AuthedMembersMemberIdChoresRoute
  '/_authed/settings/members/new': typeof AuthedSettingsMembersNewRoute
  '/_authed/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/_authed/members/$memberId/': typeof AuthedMembersMemberIdIndexRoute
  '/_authed/settings/members/$memberId/edit': typeof AuthedSettingsMembersMemberIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/calendar'
    | '/shopping'
    | '/'
    | '/meals/new'
    | '/tasks/new'
    | '/meals'
    | '/settings'
    | '/tasks'
    | '/meals/$mealId/edit'
    | '/members/$memberId/chores'
    | '/settings/members/new'
    | '/tasks/$taskId/edit'
    | '/members/$memberId'
    | '/settings/members/$memberId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/calendar'
    | '/shopping'
    | '/'
    | '/meals/new'
    | '/tasks/new'
    | '/meals'
    | '/settings'
    | '/tasks'
    | '/meals/$mealId/edit'
    | '/members/$memberId/chores'
    | '/settings/members/new'
    | '/tasks/$taskId/edit'
    | '/members/$memberId'
    | '/settings/members/$memberId/edit'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/calendar'
    | '/_authed/shopping'
    | '/_authed/'
    | '/_authed/meals/new'
    | '/_authed/tasks/new'
    | '/_authed/meals/'
    | '/_authed/settings/'
    | '/_authed/tasks/'
    | '/_authed/meals/$mealId/edit'
    | '/_authed/members/$memberId/chores'
    | '/_authed/settings/members/new'
    | '/_authed/tasks/$taskId/edit'
    | '/_authed/members/$memberId/'
    | '/_authed/settings/members/$memberId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shopping': {
      id: '/_authed/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthedShoppingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meals/': {
      id: '/_authed/meals/'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthedMealsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/new': {
      id: '/_authed/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthedTasksNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meals/new': {
      id: '/_authed/meals/new'
      path: '/meals/new'
      fullPath: '/meals/new'
      preLoaderRoute: typeof AuthedMealsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members/$memberId/': {
      id: '/_authed/members/$memberId/'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthedMembersMemberIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/edit': {
      id: '/_authed/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof AuthedTasksTaskIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/members/new': {
      id: '/_authed/settings/members/new'
      path: '/settings/members/new'
      fullPath: '/settings/members/new'
      preLoaderRoute: typeof AuthedSettingsMembersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members/$memberId/chores': {
      id: '/_authed/members/$memberId/chores'
      path: '/members/$memberId/chores'
      fullPath: '/members/$memberId/chores'
      preLoaderRoute: typeof AuthedMembersMemberIdChoresRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meals/$mealId/edit': {
      id: '/_authed/meals/$mealId/edit'
      path: '/meals/$mealId/edit'
      fullPath: '/meals/$mealId/edit'
      preLoaderRoute: typeof AuthedMealsMealIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/members/$memberId/edit': {
      id: '/_authed/settings/members/$memberId/edit'
      path: '/settings/members/$memberId/edit'
      fullPath: '/settings/members/$memberId/edit'
      preLoaderRoute: typeof AuthedSettingsMembersMemberIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedShoppingRoute: typeof AuthedShoppingRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedMealsNewRoute: typeof AuthedMealsNewRoute
  AuthedTasksNewRoute: typeof AuthedTasksNewRoute
  AuthedMealsIndexRoute: typeof AuthedMealsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
  AuthedMealsMealIdEditRoute: typeof AuthedMealsMealIdEditRoute
  AuthedMembersMemberIdChoresRoute: typeof AuthedMembersMemberIdChoresRoute
  AuthedSettingsMembersNewRoute: typeof AuthedSettingsMembersNewRoute
  AuthedTasksTaskIdEditRoute: typeof AuthedTasksTaskIdEditRoute
  AuthedMembersMemberIdIndexRoute: typeof AuthedMembersMemberIdIndexRoute
  AuthedSettingsMembersMemberIdEditRoute: typeof AuthedSettingsMembersMemberIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedShoppingRoute: AuthedShoppingRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedMealsNewRoute: AuthedMealsNewRoute,
  AuthedTasksNewRoute: AuthedTasksNewRoute,
  AuthedMealsIndexRoute: AuthedMealsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
  AuthedMealsMealIdEditRoute: AuthedMealsMealIdEditRoute,
  AuthedMembersMemberIdChoresRoute: AuthedMembersMemberIdChoresRoute,
  AuthedSettingsMembersNewRoute: AuthedSettingsMembersNewRoute,
  AuthedTasksTaskIdEditRoute: AuthedTasksTaskIdEditRoute,
  AuthedMembersMemberIdIndexRoute: AuthedMembersMemberIdIndexRoute,
  AuthedSettingsMembersMemberIdEditRoute:
    AuthedSettingsMembersMemberIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
