/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTasksRouteImport } from './routes/_authed/tasks'
import { Route as AuthedShoppingRouteImport } from './routes/_authed/shopping'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMyChoresRouteImport } from './routes/_authed/my-chores'
import { Route as AuthedMealsRouteImport } from './routes/_authed/meals'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShoppingRoute = AuthedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyChoresRoute = AuthedMyChoresRouteImport.update({
  id: '/my-chores',
  path: '/my-chores',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMealsRoute = AuthedMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/calendar': typeof AuthedCalendarRoute
  '/meals': typeof AuthedMealsRoute
  '/my-chores': typeof AuthedMyChoresRoute
  '/settings': typeof AuthedSettingsRoute
  '/shopping': typeof AuthedShoppingRoute
  '/tasks': typeof AuthedTasksRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/calendar': typeof AuthedCalendarRoute
  '/meals': typeof AuthedMealsRoute
  '/my-chores': typeof AuthedMyChoresRoute
  '/settings': typeof AuthedSettingsRoute
  '/shopping': typeof AuthedShoppingRoute
  '/tasks': typeof AuthedTasksRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/meals': typeof AuthedMealsRoute
  '/_authed/my-chores': typeof AuthedMyChoresRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/shopping': typeof AuthedShoppingRoute
  '/_authed/tasks': typeof AuthedTasksRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/calendar'
    | '/meals'
    | '/my-chores'
    | '/settings'
    | '/shopping'
    | '/tasks'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/calendar'
    | '/meals'
    | '/my-chores'
    | '/settings'
    | '/shopping'
    | '/tasks'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/calendar'
    | '/_authed/meals'
    | '/_authed/my-chores'
    | '/_authed/settings'
    | '/_authed/shopping'
    | '/_authed/tasks'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shopping': {
      id: '/_authed/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthedShoppingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-chores': {
      id: '/_authed/my-chores'
      path: '/my-chores'
      fullPath: '/my-chores'
      preLoaderRoute: typeof AuthedMyChoresRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meals': {
      id: '/_authed/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthedMealsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedMealsRoute: typeof AuthedMealsRoute
  AuthedMyChoresRoute: typeof AuthedMyChoresRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedShoppingRoute: typeof AuthedShoppingRoute
  AuthedTasksRoute: typeof AuthedTasksRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedMealsRoute: AuthedMealsRoute,
  AuthedMyChoresRoute: AuthedMyChoresRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedShoppingRoute: AuthedShoppingRoute,
  AuthedTasksRoute: AuthedTasksRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
